### ISSUE TITLE
RasterLayer input in simple mode results in an empty raster

### ISSUE THREAD

**Issue by GreatEmerald** [pierreroudier/clhs#1]
From what I have tried so far, it seems that having a RasterLayer as an input to the ```clhs()``` function, in simple mode (the default), results in an empty RasterLayer being returned. The reason for that is that the ```raster()``` function is used to turn a SpatialPointsDataFrame into a raster (https://github.com/pierreroudier/clhs/blob/master/R/clhs-raster.R#L12), however, this is not something that the ```raster``` package handles (see the manual page for ```raster```, it handles only SpatialPixels and SpatialGrid).

Instead, the function ```rasterize()``` should be used for that purpose, such as:
```
spl <- rasterize(spl, spdf, field="layer")
```

However, the usefulness of returning a raster is questionable. Why not just return the SpatialPointsDataFrame? It is much smaller, and the users could then use various functions in raster themselves to get the wanted information (for example, they might want to extract values at those locations, which is much easier to achieve with a SpatialPointsDataFrame).

**Comment by pierreroudier** [comment]
Hey thanks, very good point re: `rasterize`. And I also agree that the function should return a `SpatialPointsDataFrame` when a `sp` or `raster` object is passed to `clhs`.

I'll try to correct this as soon as I got some time in my hands. 

Cheers,

Pierre

**Comment by pierreroudier** [comment]
@GreatEmerald Hopefully this bug is solved by the [latest commit](https://github.com/pierreroudier/clhs/commit/436ff6f7af6d526e6e4ac99d1b5d9231003199e0).

Sorry for the lag!
